### ISSUE TITLE
InvalidOperationException in ParentChangedNotifier

### ISSUE THREAD

**Issue by xmedeko** [MrCircuit/XAMLMarkupExtensions#6]
Hi, after update to the newest version 1.2.1.1 I've got an error:

    System.InvalidOperationException: Sequence contains more than one element
       v System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
       v XAMLMarkupExtensions.Base.ParentChangedNotifier.ParentChanged(DependencyObject obj, DependencyPropertyChangedEventArgs args)
       v System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)

**Comment by MrCircuit** [comment]
Although I fixed it, can you provide a test case where this happens? It was not covered by our tests.

**Comment by SeriousM** [comment]
Your fix indicates that we have multiple weak references for the same
target. Could you fix the root issue instead the symptom please?
Am 24.06.2015 15:34 schrieb "Uwe Mayer" <notifications@github.com>:

**Comment by xmedeko** [comment]
It would be nice if you provide pdb files in NuGet or symbolsource.org.

Wy use MahApps project and the problem is with it's `WindowCommands`, try this example:

```xml
    <Controls:MetroWindow
        x:Class="TestProject.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:Controls="http://metro.mahapps.com/winfx/xaml/controls"
        xmlns:l="http://wpflocalizeextension.codeplex.com"
        xmlns:my="clr-namespace:TestProject"
        l:ResxLocalizationProvider.DefaultAssembly="TestProject"
        l:ResxLocalizationProvider.DefaultDictionary="Properties.Resources"
        Title="XAMLMarkupExtensions Issue#6"
        Width="400" Height="300">
    <Controls:MetroWindow.LeftWindowCommands>
        <Controls:WindowCommands ShowSeparators="False">
            <TextBlock Text="{l:Loc menuFile}" />
            <TextBlock Text="{l:Loc menuHelp}" />
        </Controls:WindowCommands>
    </Controls:MetroWindow.LeftWindowCommands>
</Controls:MetroWindow>

**Comment by xmedeko** [comment]
Also note that check in `ParentChangedNotifier`:
```cs
OnParentChangedList.Keys.FirstOrDefault(x => x.IsAlive && ReferenceEquals(x.Target, notifier));
```
Can be simplified to
```cs
    OnParentChangedList.Keys.FirstOrDefault(ReferenceEquals(x.Target, notifier));
```
Since `x.Target == null` when not alive.
